"""empty message

Revision ID: c3d96c998cf5
Revises: 
Create Date: 2017-05-19 23:32:22.255199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d96c998cf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uid', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('pword', sa.String(length=255), nullable=True),
    sa.Column('made_on', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('wish',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('wishes',
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('wid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['wid'], ['wish.pid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishes')
    op.drop_table('wish')
    op.drop_table('user')
    # ### end Alembic commands ###
